spring:
  profiles:
    active: local
  application:
    name: mock-server-admin


server:
  port: 60034
  tomcat:
    max-threads: 2000
    max-connections: 2000


#  context-path: /
---
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  rabbitmq:
      host: 172.16.0.29
      port: 5672
      username: guest
      password: guest

  freemarker:
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .tpl  #后缀名
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点



datasource:
#  url: jdbc:mysql://172.16.32.243:3306/db_mock_server?useSSL=false&useUnicode=true&characterEncoding=utf8
#  username: root
#  password: root
  url: jdbc:mysql://localhost:3306/db_mock_server?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: root
  password: Pass@123
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 100
  maxActive: 300
  minIdle: 50
  validationQuery: SELECT 1

mybatis:
#  mapper-locations: classpath:com.hualala.qa.mockserver.model.gen.mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hualala.qa.mockserver.model.gen.pojo # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml


http:
  maxTotal: 100                       #最大连接数
  defaultMaxPerRoute: 20              #并发数
  connectTimeout: 1000                #创建连接的最长时间
  connectionRequestTimeout: 500       #从连接池中获取到连接的最长时间
  socketTimeout: 10000                #数据传输的最长时间
  staleConnectionCheckEnabled: true   #提交请求前测试连接是否可用




logging:
  config: classpath:logback-local.xml



---
spring:
  profiles: pre
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  rabbitmq:
      host: 172.16.0.28
      port: 5672
      username: admin
      password: admin

  freemarker:
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .tpl  #后缀名
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点


rabbitmq:
  callbackSchedulerExchangeName: hll:qa:mockserver:callback:scheduler:exchange
  callbackSchedulerQueueName: hll:qa:mockserver:callback:scheduler:queue


  callbackDeadLetterExchangeName: hll:qa:mockserver:callback:deadletter:exchange
  callbackDeadLetterQueueName: hll:qa:mockserver:callback:deadletter:queue

  callbackJobExchangeName: hll:qa:mockserver:callback:job:exchange
  callbackJobQueueName: hll:qa:mockserver:callback:job:queue
  callbackJobRoutingKey: hll:qa:mockserver:callback:job:RoutingKey:main

  callbackResultNotifyExchangeName: hll:qa:mockserver:callback:result:notify:exchange
  callbackResultNotifyQueueName: hll:qa:mockserver:callback:result:notify:queue
  callbackResultNotifyRoutingKey: hll:qa:mockserver:callback:result:notify:RoutingKey:basekey




datasource:
  url: jdbc:mysql://172.16.32.190:3306/db_mock_server?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 100
  maxActive: 300
  minIdle: 50
  validationQuery: SELECT 1

mybatis:
  mapper-locations: classpath:com.hualala.qa.mockserver.model.gen.mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hualala.qa.mockserver.model.gen.pojo # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml

http:
  maxTotal: 100                       #最大连接数
  defaultMaxPerRoute: 20              #并发数
  connectTimeout: 1000                #创建连接的最长时间
  connectionRequestTimeout: 500       #从连接池中获取到连接的最长时间
  socketTimeout: 10000                #数据传输的最长时间
  staleConnectionCheckEnabled: true   #提交请求前测试连接是否可用


logging:
  config: classpath:logback-pre.xml



