spring:
  profiles:
    active: local
  application:
    name: mock-server-admin


server:
  port: 8110
  tomcat:
    max-threads: 2000
    max-connections: 2000


#  context-path: /
---
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  freemarker:
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .tpl  #后缀名
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点

tencent:
  skdAppid: 1400000000
  privstr: "-----BEGIN PRIVATE KEY-----\n
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfj0GG1UIewWmQcx3\n
            J2wFmkOkHv3vif7vgUcLcLWb/ayhRANCAATViQwtmRAnOG+mf04WF7M98Z9fpPVj\n
            z4xNPoXUninTg/PbSu94CGYTYWxfbA4AT8XxHST7EYcnunlhlybGwA/w\n
            -----END PRIVATE KEY-----"
  pubstr: "-----BEGIN PUBLIC KEY-----\n
           MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1YkMLZkQJzhvpn9OFhezPfGfX6T1\n
           Y8+MTT6F1J4p04Pz20rveAhmE2FsX2wOAE/F8R0k+xGHJ7p5YZcmxsAP8A==\n
           -----END PUBLIC KEY-----"
  accountType: 36862

videodatasource:
  url: jdbc:mysql://172.16.32.243:3306/tencent_video?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: root
  password: root
#  url: jdbc:mysql://localhost:3306/db_pre_k8s_op?useSSL=false&useUnicode=true&characterEncoding=utf8
#  username: root
#  password: Pass@123
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 10
  maxActive: 30
  minIdle: 5
  validationQuery: SELECT 1

mybatis:
  mapper-locations: classpath:com.hualala.api.model.gen.mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hualala.api.model.gen.pojo # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml


logging:
  config: classpath:logback-local.xml


---
spring:
  profiles: yefei
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  freemarker:
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .tpl  #后缀名
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点


tencent:
  skdAppid: 1400000000
  privstr: "-----BEGIN PRIVATE KEY-----\n
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfj0GG1UIewWmQcx3\n
            J2wFmkOkHv3vif7vgUcLcLWb/ayhRANCAATViQwtmRAnOG+mf04WF7M98Z9fpPVj\n
            z4xNPoXUninTg/PbSu94CGYTYWxfbA4AT8XxHST7EYcnunlhlybGwA/w\n
            -----END PRIVATE KEY-----"
  pubstr: "-----BEGIN PUBLIC KEY-----\n
           MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1YkMLZkQJzhvpn9OFhezPfGfX6T1\n
           Y8+MTT6F1J4p04Pz20rveAhmE2FsX2wOAE/F8R0k+xGHJ7p5YZcmxsAP8A==\n
           -----END PUBLIC KEY-----"
  accountType: 36862

videodatasource:
  url: jdbc:mysql://localhost:3306/tencent_vedio?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: yefei
  password: Yefei123456!
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 10
  maxActive: 30
  minIdle: 5
  validationQuery: SELECT 1



mybatis:
  mapper-locations: classpath:com.hualala.qa.mockserver.model.gen.mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hualala.qa.mockserver.model.gen.pojo # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml

http:
  maxTotal: 100                       #最大连接数
  defaultMaxPerRoute: 20              #并发数
  connectTimeout: 1000                #创建连接的最长时间
  connectionRequestTimeout: 500       #从连接池中获取到连接的最长时间
  socketTimeout: 10000                #数据传输的最长时间
  staleConnectionCheckEnabled: true   #提交请求前测试连接是否可用



logging:
  config: classpath:logback-pre.xml

